# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5529cce8db32dc6f1295e3c055e5d3248baa7b5e62e34009f96d3f725ff1e248afcdbb6f5ad00d1805e8e5aa38602789d934c13a434392468970cb9dd3e2e871

test:
  secret_key_base: 9286ed06025581617d99e8aaea9867e07c69147261c512e6d335545edb7706055778ba524e6c65d22c1a86822dbd1fd5707381f26cb418d6918125304862c2bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
